#!/usr/bin/python
import ovirtsdk.api
from ovirtsdk.xml import params
import sys
import time
from vmtools import VMTools
from config import Config
from getopt import getopt, GetoptError


"""
Main class to make the backups
"""


def main(argv):
    usage = "backup.py -c <config.cfg>"
    try:
        opts, args = getopt(argv, "hc:d")
        debug = False
        if not opts:
            print usage
            sys.exit(1)
        for opt, arg in opts:
            if (opt == "-h") or (opt == "--help"):
                print usage
                sys.exit(0)
            elif opt in ("-c"):
                config_file = arg
            elif opt in ("-d"):
                debug = True
    except GetoptError:
        print usage
        sys.exit(1)

    config = Config(config_file, debug)

    time_start = int(time.time())

    # Connect to server
    api = ovirtsdk.api.API(
        url=config.get_server(),
        username=config.get_username(),
        password=config.get_password(),
        insecure=True,
        debug=config.get_debug()
    )

    # Test if all VM names are valid
    for vm_from_list in config.get_vm_names():
        if not api.vms.get(vm_from_list):
            print "!!! There are no VM with the following name in your\
                    cluster: " + vm_from_list
            sys.exit(1)

    for vm_from_list in config.get_vm_names():
        print "Start backup for: " + vm_from_list

        # Get the VM
        vm = api.vms.get(vm_from_list)

        # Cleanup: Delete the cloned VM
        VMTools.delete_vm(api, config, vm_from_list)

        # Delete old backup snapshots
        VMTools.delete_snapshots(vm, config, vm_from_list)

        # Create a VM snapshot:
        try:
            print "Snapshot creation started ..."

            if not config.get_dry_run():
                vm.snapshots.add(params.Snapshot(
                    description=config.get_snapshot_description(), vm=vm))
                VMTools.wait_for_snapshot_operation(vm, config, "creation")

            print "Snapshot created"

        except Exception as e:
            print "Can't create snapshot for VM: " + vm_from_list
            print "DEBUG: " + str(e)
            sys.exit(1)

        # Clone the snapshot into a VM
        snapshots = vm.snapshots.list(
            description=config.get_snapshot_description())

        if not snapshots:
            print "!!! No snapshot found"
            sys.exit(1)

        snapshot_param = params.Snapshot(id=snapshots[0].id)
        snapshots_param = params.Snapshots(snapshot=[snapshot_param])
        print "Clone into VM started ..."

        if not config.get_dry_run():
            api.vms.add(params.VM(name=vm_from_list + config.get_vm_middle()
                                  + config.get_vm_suffix(),
                                  memory=vm.get_memory(),
                                  cluster=api.clusters.get(
                                      config.get_cluster_name()),
                                  snapshots=snapshots_param))
            VMTools.wait_for_vm_operation(api, config, "Cloning",
                                          vm_from_list)
        print "Cloning finished"
        VMTools.delete_snapshots(vm, config, vm_from_list)

    VMTools.verify_volume_attached(api, config)

    if config.get_export_volume_rotate() or VMTools.get_always(api, config):
            if VMTools.get_always(api, config):
                VMTools.delete_old_backups(api, config, vm_from_list, True)
                VMTools.volume_rotate(api, config, 'attach',
                                      VMTools.get_export_domain(api,
                                                                config,
                                                                True))
                for vm_from_list in config.get_vm_names():
                    VMTools.export_vms(api, config, vm_from_list, True)
                    print "VM exported as " + vm_from_list
                VMTools.volume_rotate(api, config, 'detach',
                                          VMTools.get_export_domain(api,
                                                                    config,
                                                                    True))

            if VMTools.get_always(api, config):
                if not (VMTools.get_export_domain(api, config, False)
                        == config.get_export_domain()['always']):
                    if config.get_export_volume_rotate():
                        VMTools.delete_old_backups(api, config, vm_from_list,
                                                   False)

                        VMTools.volume_rotate(api, config, 'attach',
                                              VMTools.get_export_domain(
                                                  api, config, False))

                        for vm_from_list in config.get_vm_names():
                            VMTools.export_vms(
                                api, config, vm_from_list, False)

                            print "VM exported as " + vm_from_list\
                                    + config.get_vm_middle()\
                                    + config.get_vm_suffix()
                        VMTools.volume_rotate(api, config, 'detach',
                                                  VMTools.get_export_domain(
                                                      api, config, False))

    else:
        print "!!! was not performed backup"
        sys.exit(1)

    for vm_from_list in config.get_vm_names():
        VMTools.delete_vm(api, config, vm_from_list)

    time_end = int(time.time())
    time_diff = (time_end - time_start)
    time_minutes = int(time_diff / 60)
    time_seconds = time_diff % 60

    print "Duration: " + str(time_minutes) + ":"\
            + str(time_seconds) + " minutes"
    print "All backups done"

    # Disconnect from the server
    api.disconnect()

if __name__ == "__main__":
    main(sys.argv[1:])
